export const LOAD_FLIGHT = 'FETCH_FLIGHT';
export const LOAD_FLIGHT_SUCCEED = 'FETCH_FLIGHT_SUCCEED';
export const LOAD_FLIGHT_FAILED = 'LOAD_FLIGHT_FAILED';
export const FILTER_FLIGHT = 'FILTER_FLIGHT';
export const FILTER_FLIGHT_SUCCEED = 'FILTER_FLIGHT_SUCCEED';
export const FILTER_FLIGHT_FAILED = 'FILTER_FLIGHT_FAILED';
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';